// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEH3zRAidrlDhs8seX_xjupXjZN5KOVHI',
    appId: '1:714072830066:web:5886953e5bb74ad54252eb',
    messagingSenderId: '714072830066',
    projectId: 'dndsystem-bce4e',
    authDomain: 'dndsystem-bce4e.firebaseapp.com',
    storageBucket: 'dndsystem-bce4e.firebasestorage.app',
    measurementId: 'G-DP2ESRNHD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA86pb1_-lUjHLsEGM20bzeONj6d4I3Kfw',
    appId: '1:714072830066:android:2f309c7fed3620eb4252eb',
    messagingSenderId: '714072830066',
    projectId: 'dndsystem-bce4e',
    storageBucket: 'dndsystem-bce4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqMO-SqldbnWqo-m7yXE51E8vQORNspe0',
    appId: '1:714072830066:ios:ace0cf2609fb72e34252eb',
    messagingSenderId: '714072830066',
    projectId: 'dndsystem-bce4e',
    storageBucket: 'dndsystem-bce4e.firebasestorage.app',
    iosBundleId: 'com.example.dndsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqMO-SqldbnWqo-m7yXE51E8vQORNspe0',
    appId: '1:714072830066:ios:ace0cf2609fb72e34252eb',
    messagingSenderId: '714072830066',
    projectId: 'dndsystem-bce4e',
    storageBucket: 'dndsystem-bce4e.firebasestorage.app',
    iosBundleId: 'com.example.dndsystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEH3zRAidrlDhs8seX_xjupXjZN5KOVHI',
    appId: '1:714072830066:web:283c3125e48854464252eb',
    messagingSenderId: '714072830066',
    projectId: 'dndsystem-bce4e',
    authDomain: 'dndsystem-bce4e.firebaseapp.com',
    storageBucket: 'dndsystem-bce4e.firebasestorage.app',
    measurementId: 'G-G5T1XF6R02',
  );
}
